[tests] Fix `test_not_null_source` in test_model
This code fixes the test `test_not_null_source` by adding
the id, which is mandatory. This fix is needed to
prevent the error:
```
sqlalchemy.exc.InternalError: (pymysql.err.InternalError)
(1364, "Field 'id' doesn't have a default value")
```

Due to:
```
sqlalchemy/sql/crud.py:695: SAWarning: Column 'identities.id' is
marked as a member of the primary key for table 'identities', but
has no Python-side or server-side default generator indicated,
nor does it indicate 'autoincrement=True' or 'nullable=True',
and no explicit value is passed.
Primary key columns typically may not store NULL.
```

Signed-off-by: Valerio Cosentino <valcos@bitergia.com>