[tests] Fix rq version and update fakeredis
This commit fixes the version of rq to <1.12 because at
1.12.0 it raises the following error in tests:
redis.exceptions.ResponseError: unknown command 'xrevrange'

It is possible an incompability with fakeredis. In this commit
this package is updated to 2.2.0, the latest compatible version
with Python 3.7.

Signed-off-by: Jose Javier Merchante <jjmerchante@bitergia.com>